### ISSUE TITLE
Equality test for labeled permutations

### ISSUE THREAD

**Issue by Fougeroc** [flatsurf/surface-dynamics#96]
If two permutations have a labels equal but with a different ranking in alphabet they are considered different.
Is it unconvenient to test whether a permutation is in a Rauzy Diagram.

```
sage: from surface_dynamics import *
sage: p1 = iet.GeneralizedPermutation(([0,1,1], [3,3,2,0,2]))
sage: G = p1.rauzy_diagram().graph()
sage: G.outgoing_edges(p1)[0][1]
0 2 1 1
3 3 2 0
sage: p2 = iet.GeneralizedPermutation(([0,2,1,1], [3,3,2,0]))
sage: p2 in G.vertices()
False
```

Or is there a cleverer way to test this ?

**Comment by Fougeroc** [comment]
I see, I should mention that the alphabet is the same.
```
sage: p2 = iet.GeneralizedPermutation(([0,2,1,1], [3,3,2,0]), alphabet=p1.alphabet())
sage: p2 in G.vertices()
True
```

I think this can lead to some misunderstanding. But maybe there is no better way.

**Comment by videlec** [comment]
Note that there are also two types of permutations: labelled and unlabelled. The latter is called reduced in `surface-dynamics`.

The equality of permutations over equal as a set but differently ordered alphabet can easily be implemented. It is fine that more permutations become equal. One has to modify the comparison method of `surface_dynamics.interval_exchanges.template.Permutation`: `__eq__`, `__ne__`, `__lt__`, `__le__`, `__gt__` and `__ge__`.

Are you willing to make a pull request?

**Comment by saraedum** [comment]
Has this been fixed in #97?

**Comment by videlec** [comment]
I think so
```
sage: from surface_dynamics import *
sage: p1 = iet.GeneralizedPermutation(([0,1,1], [3,3,2,0,2]))
sage: p2 = iet.GeneralizedPermutation(([0,2,1,1], [3,3,2,0]))
sage: p2 in p1.rauzy_diagram().graph()
True
```

**Comment by videlec** [comment]
thanks!
